  <para>The configuration file may contain the following directives:</para>

  <variablelist>
    <varlistentry>
      <term><literal>TODO</literal> <parameter>foobar</parameter></term>
      <listitem>
        <para>This is a pseudo entry in the documentation that will tell you
that this section still has to be written. Furthermore, it will remind me, that
I'll still have to write that section. To be accurate, though, I'd have to write
a configuration file parser first.</para>
      </listitem>
    </varlistentry>
  </variablelist>

<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("httpd.sgml" "article" "sect1")
End:
-->
