  <para>This software is copyrighted by Peter Simons
<email>simons@computer.org</email>. Permission is granted to use this software
as you see fit, but you may <emphasis>distribute</emphasis> it in any way. The
current version is still very experimental and I don't want it to be spread to
anybody I don't know. If you did not receive this package from my directly, you
should not have it!</para>


<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("httpd.sgml" "article" "appendix")
End:
-->
