  <cmdsynopsis>
    <command>httpd</command>
    <group>
      <arg choice="opt">-d</arg>
      <arg choice="opt">--debug</arg>
    </group>
    <group>
      <arg choice="opt">-c <replaceable>config</replaceable></arg>
      <arg choice="opt">--config-file <replaceable>config</replaceable></arg>
    </group>
  </cmdsynopsis>

<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("httpd.sgml" "article" "sect1" "title" "blockquote")
End:
-->
