  <cmdsynopsis>
    <command>httpd</command>
    <group>
      <arg choice="opt">-h</arg>
      <arg choice="opt">--help</arg>
    </group>
    <arg choice="opt">--version</arg>
    <group>
      <arg choice="opt">-d</arg>
      <arg choice="opt">--debug</arg>
    </group>
    <group>
      <arg choice="opt">-p <replaceable>number</replaceable></arg>
      <arg choice="opt">--port <replaceable>number</replaceable></arg>
    </group>
    <group>
      <arg choice="opt">-r <replaceable>path</replaceable></arg>
      <arg choice="opt">--change-root <replaceable>path</replaceable></arg>
    </group>
    <arg choice="opt">--document-root <replaceable>path</replaceable></arg>
    <group>
      <arg choice="opt">-l <replaceable>path</replaceable></arg>
      <arg choice="opt">--logfile-directory <replaceable>path</replaceable></arg>
    </group>
    <group>
      <arg choice="opt">-s <replaceable>string</replaceable></arg>
      <arg choice="opt">--server-string <replaceable>string</replaceable></arg>
    </group>
    <group>
      <arg choice="opt">-u <replaceable>uid</replaceable></arg>
      <arg choice="opt">--uid <replaceable>uid</replaceable></arg>
    </group>
    <group>
      <arg choice="opt">-g <replaceable>gid</replaceable></arg>
      <arg choice="opt">--gid <replaceable>gid</replaceable></arg>
    </group>
    <arg choice="opt">--default-page <replaceable>filename</replaceable></arg>
  </cmdsynopsis>

<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("httpd.sgml" "article" "sect1" "title" "blockquote")
End:
-->
